routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group([
    'namespace' => 'Auth'
], function () {
    // Login
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');

    // Logout
    Route::get('logout', 'LoginController@logout');
    Route::post('logout', 'LoginController@logout')->name('logout');

    // Request a password reset
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

    // Reset a password
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');

    Route::get('email/resend', 'VerificationController@resend')->name('verification.resend');
    Route::get('email/verify/{id}', 'VerificationController@verify')->name('verification.verify');
});

Route::group([
    'namespace'  => 'Dashboard',
    'prefix'     => 'dashboard',
    'middleware' => 'auth',
], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard.home');

    Route::get('/quote', 'QuoteController@index')->name('dashboard.quotes.index');
    Route::get('/quote/new', 'QuoteController@showCreateForm')->name('dashboard.quotes.createForm');
    Route::post('/quote/new', 'QuoteController@store')->name('dashboard.quotes.store');
    Route::get('/quote/{quote}', 'QuoteController@showEditForm')->name('dashboard.quotes.editForm');
    Route::post('/quote/{quote}', 'QuoteController@update')->name('dashboard.quotes.update');
    Route::delete('/quote/{quote}', 'QuoteController@delete')->name('dashboard.quotes.delete');
    //Route::restore('/quotes/{quote}', 'QuoteController@restore')->name('dashboard.quotes.restore');

    Route::get('/author', 'AuthorController@index')->name('dashboard.authors.index');
    Route::get('/author/new', 'AuthorController@showCreateForm')->name('dashboard.authors.createForm');
    Route::post('/author/new', 'AuthorController@store')->name('dashboard.authors.store');
    Route::get('/author/{quote}', 'AuthorController@showEditForm')->name('dashboard.authors.editForm');
    Route::post('/author/{quote}', 'AuthorController@update')->name('dashboard.authors.update');
    Route::delete('/author/{quote}', 'AuthorController@delete')->name('dashboard.authors.delete');
    //Route::restore('/author/{quote}', 'AuthorController@restore')->name('dashboard.authors.restore');

    Route::get('/settings', 'UserController@index')->name('dashboard.user.settings');
    Route::post('/settings', 'UserController@updateSettings')->name('dashboard.user.update');
    Route::post('/settings/avatar', 'UserController@updateAvatar')->name('dashboard.user.update_avatar');
});


Route::get('/random', 'QuoteController@random')->name('quotes.random');
Route::get('/quote/{author}', 'QuoteController@randomByAuthor')->name('quotes.author');
Route::get('/quote/{author}/{quote}', 'QuoteController@show')->name('quotes.show');

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Builder;

class Author extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'authors';

    /**
     * The primary key for the model
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'int';

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'keyname';
    }

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'uid',
        'name',
        'keyname',
    ];

    /**
     * The attributes that should be cast to native types
     * E.g. always cast a number as integer instead
     * of a string
     *
     * Your options are:
     * integer, real, float, double, string,
     * boolean, object, array, collection,
     * date, datetime, timestamp
     *
     * @var array
     */
    protected $casts = [
        //
    ];

    /**
     * The attributes that should be mutated to dates
     * E.g. deleted_at, published_at, etc
     *
     * @var array
     */
    protected $dates = [
        //
    ];

    /**
     * The attributes that should be hidden for arrays
     *
     * @var array
     */
    protected $hidden = [
        //
    ];

    /**
     * The accessors to append to the model's array form
     *
     * @var array
     */
    protected $appends = [
        //
    ];

    /**
     * Boot function for Author model
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model)
        {
            $model->setRandomUid();
            $model->setAuthorKeyname();
        });
    }

    /*
    |--------------------------------------------------------------------------
    | Private/Internal Methods
    |--------------------------------------------------------------------------
    |
    | The following methods are meant to be helpers specific
    | to this model.
    |
    */

    //

    /*
    |--------------------------------------------------------------------------
    | Accessors and Mutators
    |--------------------------------------------------------------------------
    |
    | These are methods used to alter existing properties before returning
    | them or to create pseudo-properties for the model.
    |
    */

    /**
     * Ensure that a random Universal ID is set for this model.
     *
     * @return void
     */
    public function setRandomUid()
    {
        if ($this->uid == null || ! property_exists($this, 'uuid')) {
            $this->uid = bin2hex(random_bytes(6));
        }
    }

    /**
     * Ensure the Author's name is transformed to a web-safe form.
     *
     * @return void
     */
    public function setAuthorKeyname()
    {
        if ($this->keyname == null || ! property_exists($this, 'keyname')) {
            $this->keyname = str_slug($this->name);
        }
    }

    /*
    |--------------------------------------------------------------------------
    | Scopes
    |--------------------------------------------------------------------------
    |
    | These are methods that are an alias to more complicated operations
    | to a simple Eloquent method for the model.
    |
    */

    /**
     * Scope to allow quick searching by Author name.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $name  Author's name
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeByName($query, $name): Builder
    {
        return $query->where('keyname', str_slug($name));
    }

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    |
    | Here you specify relations between this model and other models.
    |
    */

    public function quotes(): HasMany
    {
        return $this->hasMany(Quote::class);
    }
}

app/Http/Controllers/Dashboard/AuthorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Author;
use App\Http\Controllers\Controller;
use App\Repositories\AuthorRepository;

use Illuminate\Http\Request;

class AuthorController extends Controller
{
    public $authorRepo;

    public function __construct(AuthorRepository $authorRepo)
    {
        $this->authorRepo = $authorRepo;
    }

    public function index()
    {
        $data = [
            'authors' => Author::withCount('quotes')->paginate(),
        ];

        return view('dashboard.authors.index')->with($data);
    }

    public function showCreateForm()
    {
        return view('dashboard.authors.create');
    }

    public function store(Request $request)
    {
        if ($author = Author::byName($request->input('name'))->first()) {
            return response()->json($author);
        }
        $author = $this->authorRepo->create(['name' => $request->input('name')]);
        return response()->json($author);
    }

    public function showEditForm(Author $author)
    {
        $data = [
            'author' => $author,
        ];
        return view('dashboard.authors.edit')->with($data);
    }

    public function update(Author $author)
    {
        //
    }

    public function delete(Author $author)
    {
        //
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Quote;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {
        $data = Cache::remember('quotes.stats', 60, function () {
            $numberOfAuthors = DB::table('authors')->select('uid')->count();
            $numberOfQuotes = DB::table('quotes')->select('uid')->count();

            return [
                'numberOfAuthors' => $numberOfAuthors,
                'numberOfQuotes'  => $numberOfQuotes,
                'cached_at'       => date('Y-m-d H:i:s'),
            ];
        });

        return view('dashboard.index')->with($data);
    }
}

app/Http/Controllers/Dashboard/QuoteController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\AuthorRepository;
use App\Repositories\QuoteRepository;
use App\Author;
use App\Quote;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class QuoteController extends Controller
{
    public $authorRepo;

    public $quoteRepo;

    public function __construct(AuthorRepository $authorRepo, QuoteRepository $quoteRepo)
    {
        $this->authorRepo = $authorRepo;
        $this->quoteRepo = $quoteRepo;
    }

    public function index()
    {
        $data = [
            'quotes' => Quote::with('author')->paginate(),
        ];

        return view('dashboard.quotes.index')->with($data);
    }

    public function showCreateForm()
    {
        return view('dashboard.quotes.create');
    }

    public function store(Request $request)
    {
        $quote = $this->quoteRepo->create($request->only(['body_markdown', 'author_id', 'year']));
        Cache::forget('quotes.stats');
        return response()->json($quote);
    }

    public function showEditForm(Quote $quote)
    {
        $quote->load('author');

        $data = [
            'quote' => $quote,
            'authors' => Author::all(),
        ];

        return view('dashboard.quotes.edit')->with($data);
    }

    public function update(Quote $quote)
    {
        return $this->quoteRepo->update($quote, request()->only(['body_markdown', 'author_uid', 'year']));
    }

    public function delete(Quote $quote)
    {
        //
    }

    public function restore(Quote $quote)
    {
        //
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserUpdateRequest;
use App\User;

class UserController extends Controller
{
    public function index()
    {
        $data = [
            'user' => auth()->user(),
        ];

        return view('dashboard.settings')->with($data);
    }

    public function updateSettings(UserUpdateRequest $request)
    {
        $requestData = $request->only('name', 'email');
        $user = auth()->user();
        $user->update($requestData);
        return $user;
    }

    public function updateAvatar()
    {
        return request()->all();
    }
}

resources/views/dashboard/authors/edit.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="flex">
        @component('components/material-card', ['title' => "Author {$author->uid}", 'headerColor' => 'indigo-dark'])
            @slot('body')
            <!-- form -->
                <div class="flex flex-col w-full">
                    <form id="form_edit-author" action="{{ route('dashboard.authors.update', [$author->uid]) }}" method="POST">
                        @csrf

                        <input type="text" id="name" name="name" value="{{ $author->name }}">
                    </form>
                </div>
            @endslot
        @endcomponent
    </div>

@endsection

resources/views/dashboard/authors/index.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="flex">
        @component('components/material-card', ['title' => 'All Authors', 'headerColor' => 'indigo-dark'])
            @slot('body')
            <!-- form -->
                <div class="flex flex-col w-full">
                    <div class="flex flex-row">
                        <div class="flex flex-row w-1/2">
                            {{ $authors->links() }}
                        </div>

                        <div class="flex justify-end w-1/2">
                            <button class="threeD-button threeD-button-red" disabled>
                                <i class="fa fa-trash-o mr-2"></i> Trash Selected
                            </button>
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-md-12">
                            <table class="table w-full mb-4">
                                <thead>
                                    <tr class="bg-grey-darkest text-white">
                                        <th class="p-3">&nbsp;</th>
                                        <th class="text-left pl-6 pr-3 py-3">Name</th>
                                        <th class="p-3">Quote Count</th>
                                        <th class="p-3">&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach ($authors as $author)
                                    <tr>
                                        <td class="p-3">
                                            <div class="form-check">
                                                <input class="form-check-input position-static" type="checkbox" id="" value="groupChecks" aria-label="...">
                                            </div>
                                        </td>
                                        <td>{{ $author->name }}</td>
                                        <td class="text-center">{{ $author->quotes_count }}</td>
                                        <td class="d-flex flex-row-reverse">
                                            <a href="{{ route('dashboard.authors.editForm', [$author->uid]) }}" class="btn btn-primary mr-2">
                                                @include('partials.svgs.edit', ['width' => '16'])
                                            </a>
                                            <button class="btn btn-danger">
                                                @include('partials.svgs.trash-2', ['width' => '16'])
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            {{ $authors->links() }}
                        </div>
                    </div>
                @endslot
            </div>
        @endcomponent
    </div>

@endsection